spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    template:
      mandatory: true
    publisher-confirm-type: correlated
    ## 消费端配置
    listener:
      simple:
        concurrency: 5
        ## manual:手动 ack（确认）
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1
        retry:
          ##重试机制
          #开启消费者(程序出现异常的情况下会,捕获异常重试将不生效)进行重试
          enabled: true
          #最大重试次数
          max-attempts: 5
          #最大间隔时间
          max-interval: 30000ms
          #重试间隔时间 3秒
          initial-interval: 10000ms
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/rabbitmq?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    postgres:
      url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: 1
      driverClassName: org.postgresql.Driver
      type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8001
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.pd.producer
  mapper-locations: classpath*:/mappers/*.xml
  type-handlers-package: com.pd.producer.config
logging:
  level:
    tk:
      mybatis: trace
