server:
  port: 8081 # 防止和服务端的端口冲突
  servlet:
    session:
      cookie:
        # 防止COOKIE冲突
        name: 'SSO-CLIENT-SESSION-ID'
# 授权服务器地址：
oauth2-server-url: http://localhost:8080
# 授权服务器的相关配置
security:
  oauth2:
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
    client:
      client-id: admin
      client-secret: 112233
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token