server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?charcaterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.pd.jwt.entity
  mapper-locations: classpath:com/pd/jwt/mapper/*.xml

logging.level.com.pd.jwt.dao: debug
